name: Build sd-cli only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.27
        with:
          cuda: '12.4.1'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DSD_CUDA=ON

      - name: Build sd-cli only
        run: cmake --build build --target sd-cli --parallel

      - name: Upload sd-cli
        uses: actions/upload-artifact@v4
        with:
          name: sd-cli
          path: |
            build/bin/sd-cli.exe
            build/bin/*.dll
